enum TimeUnit {
  days
  hours
  minutes
  seconds
  milliseconds
  microseconds
  nanoseconds
}

type SchedulingParameters @embedded {
  amount: Float!
  unit: TimeUnit!
}

type CrawlingQuery {
  keyword: String!
  schedule: SchedulingParameters!
  executions: [Time]
}

type Query {
  allCrawlingQueries: [CrawlingQuery!]
}

